name: Main
on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
      options: --init --privileged
    steps:
      - name: tmate
        uses: mxschmitt/action-tmate@v3
