name: Main
on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: docker-images
          github-token: ${{ github.token }}
          repository: msys2/msys2-docker
          run-id: 9592572891
      - name: tmate
        uses: mxschmitt/action-tmate@v3
